batch_size: 128
batch_size_val: 256
epochs: 60
lr_init: 1e-3
weight_decay: 1e-4
mixup_alpha: 0.2
patience: 10
t0_factor: 5            # CosineAnnealingWarmRestarts の T_0 係数
device: gpu

# Early stopping & 出力
metric_name: val_loss