data:
  n_splits: 5
  raw_dir: ../data
  export_dir: output
  random_seed: 42
  max_seq_len: null          # ★pad_percentile=95から自動決定（ベースと同じ）
  pad_percentile: 95
  pad_value: 0.0
  truncate_mode_train: head  # ★長い系列は先頭から切る（ベースは [:pad_len] なのでhead）
  truncate_mode_val: head    # ★検証も同様
  tof_in_channels: 5
  tof_null_thresh: null

train:
  batch_size: 64             # ★BATCH_SIZE=64
  batch_size_val: 64
  mixup_alpha: 0.4           # ★Beta(0.4,0.4)
  mixup_prob: 0.5            # ★IMUのみMixUpをp=0.5で（collate/training_step対応済み前提）
  lr_init: 1e-3              # ★LR_INIT=1e-3
  min_lr: 1e-6               # plateauでは未使用でもOK
  weight_decay: 1e-4         # ★WD=1e-4
  epochs: 100                # ★EPOCHS=100
  warmup_epochs: 1           # plateauなら実質未使用
  device: cuda
  patience: 30               # ★EarlyStopping(patience)=20（f1_avg監視前提）
  num_workers: 4

scheduler:
  name: plateau              # ★Adam + ReduceLROnPlateau
  monitor: val/neg_f1_18     # ★(1 - F1_18) を監視＝ベースの scheduler.step(1 - f1_18) と一致
  mode: min                  # ★最小化
  factor: 0.5
  patience: 3
  threshold: 0.0
  threshold_mode: rel
  cooldown: 0
  min_lr_sched: 0.0
  verbose: true

imu_dim: null                # 実行時にセット
num_classes: null            # 実行時にセット

tof:
  in_channels: 5
  out_dim: 32

cnn:
  multiscale:
    kernel_sizes: [3, 5, 7]
    out_per_kernel: 12
  residual:
    out_channels: 48
    num_blocks: 2
  share_branch: false        

rnn:
  hidden_size: 128
  num_layers: 2
  bidirectional: true
  dropout: 0.2

meta:
  proj_dim: 64
  dropout: 0.2
  stats_per_channel: 5

noise_std: 0.09

head:
  hidden: 512
  dropout: 0.5

aug:
  no_aug: true

  # 時間方向
  p_time_shift: 0.7
  max_shift_ratio: 0.1
  p_time_warp: 0.5
  warp_min: 0.9
  warp_max: 1.1
  p_block_dropout: 0.5
  n_blocks: [1, 2]
  block_len: [2, 5]

  # IMU系
  p_imu_jitter: 0.9
  imu_sigma: 0.03
  p_imu_scale: 0.5
  imu_scale_sigma: 0.03
  p_imu_drift: 0.5
  drift_std: 0.003
  drift_clip: 0.25
  p_imu_small_rot: 0.0   # 使うなら 0.2 など
  rot_deg: 5.0

  # ToF系
  p_tof_ch_drop: 0.2
  p_tof_erasing: 0.3
  erase_hw: [[2, 4], [2, 4]]   # [[eh_min, eh_max], [ew_min, ew_max]]
  n_erase: [1, 2]
  p_tof_shift: 0.3
  p_tof_gain_noise: 0.7
  tof_gain: [0.95, 1.05]
  tof_sigma: 0.01

  pad_value: 0.0


# aug:
#   no_aug: false  # ← ここは false のままでも、下をこの値にすれば拡張は掛からない
#
#   # 時間方向
#   p_time_shift: 0.0
#   max_shift_ratio: 0.0
#   p_time_warp: 0.0
#   warp_min: 1.0
#   warp_max: 1.0
#   p_block_dropout: 0.0
#   n_erase: [0, 0]      # 任意（p=0なら影響なし）
#   n_blocks: [0, 0]     # 任意（p=0なら影響なし）
#   block_len: [0, 0]    # 任意
#
#   # IMU系
#   p_imu_jitter: 0.0
#   imu_sigma: 0.0
#   p_imu_scale: 0.0
#   imu_scale_sigma: 0.0
#   p_imu_drift: 0.0
#   drift_std: 0.0
#   drift_clip: 0.0
#   p_imu_small_rot: 0.0
#   rot_deg: 0.0
#
#   # ToF系
#   p_tof_ch_drop: 0.0
#   p_tof_erasing: 0.0
#   erase_hw: [[0, 0], [0, 0]]  # 任意（p=0なら影響なし）
#   n_erase: [0, 0]
#   p_tof_shift: 0.0
#   p_tof_gain_noise: 0.0
#   tof_gain: [1.0, 1.0]
#   tof_sigma: 0.0
#
#   # その他
#   pad_value: 0.0  # 使われないがそのままでOK
#
# # （MixUpも完全に無効化したい場合）
# # train:
# #   mixup_alpha: 0.0
