data:
  n_splits: 5
  raw_dir: ../data
  export_dir: output
  random_seed: 42
  max_seq_len: null
  pad_percentile: 95
  pad_value: 0.0
  truncate_mode_train: tail  # random/head/tail/center
  truncate_mode_val: tail     # random/head/tail/center
  tof_in_channels: 5
  tof_null_thresh: 250

train:
  batch_size: 128
  batch_size_val: 128
  mixup_alpha: 0.0
  lr_init: 5e-4
  min_lr: 1e-5
  weight_decay: 3e-3
  epochs: 100
  warmup_epochs: 30
  device: cuda
  patience: 40
  num_workers: 4
  scheduler:
    # name: warmup_cosine    # ← これなら AdamW + WarmupCosine
    name: plateau            # ← これなら Adam + ReduceLROnPlateau
    monitor: val_acc    # Loss なら "val_loss"
    mode: max                # Loss の時は "min"
    factor: 0.5
    patience: 3
    threshold: 0.0005
    threshold_mode: rel
    cooldown: 0
    min_lr: 1e-6
    verbose: true

imu_dim: null         # ← 実行時にセット（例: 9）
num_classes: null     # ← 実行時にセット（例: 23）

tof:
  in_channels: 5
  out_dim: 32

cnn:
  multiscale:
    kernel_sizes: [3, 5, 7]
    out_per_kernel: 12
  residual:
    out_channels: 48
    num_blocks: 2
  share_branch: false   # true で全IMU軸のCNNを重み共有

rnn:
  hidden_size: 128
  num_layers: 2
  bidirectional: true
  dropout: 0.2

meta:
  proj_dim: 64
  dropout: 0.2
  stats_per_channel: 5   

noise_std: 0.09

head:
  hidden: 512
  dropout: 0.5

aug:
  no_aug: true

  # 時間方向
  p_time_shift: 0.7
  max_shift_ratio: 0.1
  p_time_warp: 0.5
  warp_min: 0.9
  warp_max: 1.1
  p_block_dropout: 0.5
  n_blocks: [1, 2]
  block_len: [2, 5]

  # IMU系
  p_imu_jitter: 0.9
  imu_sigma: 0.03
  p_imu_scale: 0.5
  imu_scale_sigma: 0.03
  p_imu_drift: 0.5
  drift_std: 0.003
  drift_clip: 0.25
  p_imu_small_rot: 0.0   # 使うなら 0.2 など
  rot_deg: 5.0

  # ToF系
  p_tof_ch_drop: 0.2
  p_tof_erasing: 0.3
  erase_hw: [[2, 4], [2, 4]]   # [[eh_min, eh_max], [ew_min, ew_max]]
  n_erase: [1, 2]
  p_tof_shift: 0.3
  p_tof_gain_noise: 0.7
  tof_gain: [0.95, 1.05]
  tof_sigma: 0.01

  pad_value: 0.0
