model:
  name: lstmgru
  num_classes: 18
  num_channels: 15

meta:
  proj_dim: 32
  dropout: 0.20

cnn:
  multiscale:
    out_channels: 36
    out_per_kernel: 12        # 各カーネルあたりの出力チャネル
    kernel_sizes: [3, 5, 7]
  se:
    out_channels: 48          # 各チャンネル枝の最終出力チャネル
    drop: 0.30

rnn:
  hidden_size: 128
  num_layers: 2
  dropout: 0.20
  bidirectional: true

lmu:
  hidden_size: 128
  memory_size: 256
  theta: 127
  out_size: 128               # LMUの時間方向出力次元（実装に合わせて変更可）

noise:
  std: 0.09

head:
  hidden: 512
  dropout: 0.50
