data:
  name: cmi
  raw_dir: ../data
  train_csv: train.csv
  test_csv: test.csv
  export_dir: output
  pad_percentile: 95
  val_ratio: 0.2
  random_seed : 42
  n_splits: 5

train:
  batch_size: 128
  batch_size_val: 256
  epochs: 100
  lr_init: 1e-3
  weight_decay: 1e-4
  mixup_alpha: 0.2
  patience: 30
  t0_factor: 5            # CosineAnnealingWarmRestarts の T_0 係数
  device: cuda
  dense_drop: 0.2
  conv_drop: 0.2
  noise_std: 0.09
  mode: 18_class

  # Early stopping & 出力
  metric_name: val_loss

model:
  model:
    name: lstmgru_tcn_concat
    num_classes: 18
    num_channels: 360          # = imu_dim + tof_dim （要一致）

  modalities:
    imu_dim: 15
    tof_dim: 345

  meta:
    proj_dim: 32
    dropout: 0.2

  cnn:
    multiscale:
      out_per_kernel: 12
      kernel_sizes: [3, 5, 7]
    se:
      out_channels: 48
      drop: 0.3
    pool_sizes: [2, 2]

  branches:
    imu:
      filters:  [64, 128]
      kernels:  [3, 5]
      dropouts: [0.1, 0.1]
    tof:
      filters:  [64, 128]
      kernels:  [3, 3]
      dropouts: [0.2, 0.2]

  # ← 追加: 片方だけ使うRNNの種類（'gru' or 'lstm'）
  rnn:
    type: gru               # "gru" | "lstm"
    hidden_size: 128
    num_layers: 2
    dropout: 0.2
    bidirectional: true

  # ← 追加: TCNスタック（RNNと並列で使い、最後にconcat）
  tcn:
    kernel_size: 3
    n_layers: 5
    base_dilation: 1
    dropout: 0.2
    out_channels: null      # null→CNN出力と同次元で軽量

  noise:
    std: 0.09

  head:
    hidden: 512
    dropout: 0.5

  timemix:
    out_channels: null     # → 自動で入力次元に合わせる
    dropout: 0.10
    activation: gelu

  # ★ 新設: Co-Attention（IMU⇄ToF）
  coattn:
    dim: 256               # 内部埋め込み
    num_heads: 4
    dropout: 0.10



aug:
  no_aug: false
  p_time_shift: 0.75
  max_shift_ratio: 0.21
  p_time_warp: 0.0
  warp_min: 0.90
  warp_max: 1.10
  p_block_dropout: 0.16
  n_blocks:
  - 2
  - 2
  block_len: 
  - 5
  - 7
  p_imu_jitter: 0.26
  imu_sigma: 0.02
  p_imu_scale: 0.35
  imu_scale_sigma: 0.08
  p_imu_drift: 0.19
  drift_std: 0.001
  drift_clip: 0.43
  p_imu_small_rot: 0.33
  rot_deg: 5.5
  pad_value: 0.0
