data:
  name: cmi
  raw_dir: ../data
  train_csv: train.csv
  test_csv: test.csv
  export_dir: output
  pad_percentile: 95
  val_ratio: 0.2
  random_seed : 42
  n_splits: 5

train:
  batch_size: 128
  batch_size_val: 256
  epochs: 100
  lr_init: 1e-3
  weight_decay: 1e-4
  mixup_alpha: 0.2
  patience: 30
  t0_factor: 5            # CosineAnnealingWarmRestarts の T_0 係数
  device: cuda
  dense_drop: 0.2
  conv_drop: 0.2
  noise_std: 0.09
  fold: 0

  # Early stopping & 出力
  metric_name: val_loss

model:
  model:
    name: lstmgru
    num_classes: 18
    num_channels: 15

  meta:
    proj_dim: 32
    dropout: 0.20

  cnn:
    multiscale:
      out_per_kernel: 12        # 12 × len([3,5,7]) = 36ch をコード側で算出
      kernel_sizes: [3, 5, 7]
    se:
      out_channels: 48          # 各チャンネル枝の最終出力チャネル
      drop: 0.30
      
    pool_sizes: [2, 2]        # MaxPool1d を2回通す想定 → L_out ≈ floor(L/4)

  rnn:
    hidden_size: 128
    num_layers: 2
    dropout: 0.20
    bidirectional: true

  noise:
    std: 0.09

  head:
    hidden: 512
    dropout: 0.50

aug:
  no_aug: false

  # 時間方向
  p_time_shift: 0.5 #0.0
  max_shift_ratio: 0.2 #0.0
  p_time_warp: 0.0 #0.0
  warp_min: 0.9 #1.0  
  warp_max: 1.1 #1.0
  p_block_dropout: 0.0 #0.0
  n_blocks: [1, 2] # [0, 0]
  block_len: [2, 5] # [0, 0]

  # IMU系
  p_imu_jitter: 0.5 #0.0
  imu_sigma: 0.09  #0.0
  p_imu_scale: 0.5 #0.0
  imu_scale_sigma: 0.09 #0.0
  p_imu_drift: 0.5 #0.0
  drift_std: 0.003 #0.0
  drift_clip: 0.25 #0.0
  p_imu_small_rot: 0.0   # 使うなら 0.2 など
  rot_deg: 5.0 #0.0

  pad_value: 0.0